jenkins:
  systemMessage: "🚀 This Jenkins instance is automatically configured via code."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin123
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('book-happy-path-tests') {
        definition {
          cpsScm {
            scm {
              git {
                remote { url('https://github.com/kartalali/api-bookstore-tests.git') }
                branches('*/main')
              }
              scriptPath('Jenkinsfile-happy')
            }
          }
        }
      }
  - script: >
      pipelineJob('book-negative-tests') {
        definition {
          cpsScm {
            scm {
              git {
                remote { url('https://github.com/kartalali/api-bookstore-tests.git') }
                branches('*/main')
              }
              scriptPath('Jenkinsfile-negative')
            }
          }
        }
      }
  - script: >
      pipelineJob('book-edge-case-tests') {
        definition {
          cpsScm {
            scm {
              git {
                remote { url('https://github.com/kartalali/api-bookstore-tests.git') }
                branches('*/main')
              }
              scriptPath('Jenkinsfile-edge')
            }
          }
        }
      }