jenkins:
  systemMessage: "🚀 This Jenkins instance is automatically configured via code."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin123
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('bookstore-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/kartalali/api-bookstore-tests.git')
                }
                branches('*/main')
              }
              scriptPath('Jenkinsfile')
            }
          }
        }
      }