services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc.yaml:/var/jenkins_home/casc.yaml
      - ./plugins:/var/jenkins_home/plugins
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    restart: always

volumes:
  jenkins_home: